# Site settings
title: Elliot John Voris
email: elliot@voris.me
description: "Faith. Family. Technology."
baseurl: ""
url: "http://elliot.voris.me"
twitter_username: ElliotFriend
github_username:  ElliotFriend
facebook_username:  ElliotFriend
youtube_username: ElliotFriend

# Build settings
markdown: kramdown
#highlighter: pygments
permalink: /blog/:year/:month/:day/:title
exclude: ["node_modules"]
exclude: [vendor]

# Collections settings
collections:
  videos:
    output: true
    permalink: /video/:title/
