# Site settings
title: Elliot John Voris
email: elliot@voris.me
description: "I'm Elliot. I'm your friend."
baseurl: ""
url: "http://elliot.voris.me"
twitter_username: ElliotFriend
github_username:  ElliotFriend
facebook_username:  ElliotFriend
youtube_username: ElliotFriend

# Github settings
repository: ElliotFriend/elliotfriend.github.io
gems: ['jekyll-github-metadata']

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /blog/:year/:month/:day/:title
exclude: ["node_modules"]
exclude: [vendor]

# Collections settings
collections:
  videos:
    output: true
    permalink: /video/:title/
